#!/usr/bin/env python3
"""Deterministic fixture generator, manifest writer and verifier (Python 3 stdlib only).

Unit: 1 MiB = 2**20 bytes everywhere (docs/BENCHMARK.md section 1).
E-1 skeleton fixtures: html_5mib, html_5mib_gz, html_50mib. E-2 adds late_landmark; the slow-drip and\nredirect-chain responses are generated by serve.py from constants here (no file, so no hash).

  fixtures.py generate [--dir DIR]           write fixtures into DIR (default bench/fixtures)
  fixtures.py write-manifest [--dir DIR]     regenerate manifest.json from DIR (review the diff!)
  fixtures.py verify [--dir DIR]             exit 2 on any missing file, size or sha256 mismatch
"""
import argparse, gzip, hashlib, json, os, random, sys

MIB = 1024 * 1024
HERE = os.path.dirname(os.path.abspath(__file__))
MANIFEST = os.path.join(HERE, "manifest.json")
SEED = 1
WORDS = "lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua".split()
HEAD = ("<!doctype html><html><head><meta charset=utf-8><title>Fixture</title><style>body{font:14px sans-serif}</style>"
        "<script>var x=1;</script></head><body><nav><a href='/'>Home</a></nav><main>")
FOOT = "</main></body></html>"
# Sizes: the 5 MiB fixture is 1 KiB under the 5 MiB cap so a correct server does not answer too_large.
SIZES = {"html_5mib": 5 * MIB - 1024, "html_50mib": 50 * MIB}
LATE_SIZE = 5 * MIB - 1024   # late-landmark page: same size class as html_5mib
REDIR_BODY = 32 * 1024        # body of each of the 5 redirect hops (redirect-chain scenario)
REDIR_FINAL = 4 * 1024        # body of the final 200
HOSTILE_SIZE = 2 * MIB - 4096  # fix-pass 1: the attrs page sits just under the 2 MiB tokenizer limit, so the limit alone never trips on it
# The attrvalue page is a page that must CONVERT, and it sat only ~4 KiB under the converter-limit cliff (a small change to the
# framing or the limit would flip it to converter_limit and INVALIDate the scenario). Final cleanup: 1.75 MiB, 12.5% below 2 MiB.
# It tests the same thing (one attribute value that is a large fraction of the tokenizer limit, held whole by the tokenizer).
ATTRVALUE_SIZE = 7 * MIB // 4


def hostile_body(kind):
    """Adversarial-page bodies for the hostile-* scenarios (generated by serve.py, no file, no manifest hash; the
    bytes are a pure function of `kind` and HOSTILE_SIZE). 'attrs': ONE start tag of ~1.9 MiB of tiny attributes
    (`<div a a a ...>`); before the attribute guard this cost ~114 MB of RSS per fetch (architect B2). 'attrvalue':
    ONE attribute value of ~1.75 MiB (legitimate shape: converts, bounded by the tokenizer limit)."""
    pre, post = b"<!doctype html><html><body><p>before</p>", b"<p>after</p></body></html>"
    if kind == "attrs":
        head, tail = b"<div ", b">hostile</div>"
        n = (HOSTILE_SIZE - len(pre) - len(post) - len(head) - len(tail)) // 2
        return pre + head + b"a " * n + tail + post
    if kind == "attrvalue":
        head, tail = b'<img alt="', b'" src=/x.png>'
        n = ATTRVALUE_SIZE - len(pre) - len(post) - len(head) - len(tail)
        return pre + head + b"z" * n + tail + post
    raise ValueError(kind)


def html_chunks(total, seed=SEED):
    """Yield ASCII HTML as bytes, exactly `total` bytes, byte-identical per (total, seed)."""
    rng = random.Random(seed)
    words = lambda n: " ".join(rng.choice(WORDS) for _ in range(n))
    written, i = len(HEAD), 0
    yield HEAD.encode()
    while True:
        s = (f"<section class='c{i}'><h2>Heading {i}</h2><p>{words(60)} <a href='https://example.com/{i}'>link {i}</a> "
             f"<em>{words(5)}</em> <strong>{words(4)}</strong></p><ul><li>{words(8)}</li><li>{words(8)}</li>"
             f"<li><code>{words(3)}</code></li></ul><div><div><span>{words(12)}</span></div></div></section>\n")
        if written + len(s) + len(FOOT) + 7 > total:
            break
        yield s.encode(); written += len(s); i += 1
    pad = total - written - len(FOOT)  # >= 7 by the loop condition
    yield ("<!--" + "x" * (pad - 7) + "-->").encode()
    yield FOOT.encode()


def late_chunks(total, seed=SEED + 1):
    """Late-landmark page: nearly all bytes are navigation div soup and the only <main> landmark (the article)
    arrives in the last few KiB, so a boilerplate detector must hold back nearly the whole document. Exactly `total` bytes."""
    rng = random.Random(seed)
    words = lambda n: " ".join(rng.choice(WORDS) for _ in range(n))
    tail = ("<main><article><h1>Late landmark</h1>" + "".join(f"<p>{words(40)}</p>" for _ in range(8)) + "</article></main></body></html>").encode()
    head = b"<!doctype html><html><head><meta charset=utf-8><title>Late</title></head><body>"
    written, i = len(head), 0
    yield head
    while True:
        s = (f"<div class='nav{i}'><ul><li><a href='/p{i}'>{words(3)}</a></li><li><a href='/q{i}'>{words(3)}</a></li></ul>"
             f"<div><div><span>{words(20)}</span></div></div></div>\n")
        if written + len(s) + len(tail) + 7 > total:
            break
        yield s.encode(); written += len(s); i += 1
    pad = total - written - len(tail)
    yield ("<!--" + "x" * (pad - 7) + "-->").encode()
    yield tail


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def generate(d):
    os.makedirs(d, exist_ok=True)
    for name, size in SIZES.items():
        with open(os.path.join(d, name + ".html"), "wb") as f:
            for c in html_chunks(size):
                f.write(c)
    with open(os.path.join(d, "late_landmark.html"), "wb") as f:
        for c in late_chunks(LATE_SIZE):
            f.write(c)
    src = os.path.join(d, "html_5mib.html")
    with open(src, "rb") as fi, open(os.path.join(d, "html_5mib.html.gz"), "wb") as fo:
        # mtime=0 and fixed level, but the compressed bytes still depend on the zlib build, so the manifest
        # pins the DECOMPRESSED payload (deterministic) and only bounds the compressed size.
        with gzip.GzipFile(filename="", mode="wb", fileobj=fo, compresslevel=6, mtime=0) as g:
            g.write(fi.read())


FILES = {"html_5mib": "html_5mib.html", "html_5mib_gz": "html_5mib.html.gz", "html_50mib": "html_50mib.html", "late_landmark": "late_landmark.html"}


# The gz fixture is checked by decompressing it. Its compressed size only has to sit in this band: well above
# nothing (real compression happened) and far below the 5 MiB cap (wire bytes < decompressed bytes).
GZ_SIZE_MIN, GZ_SIZE_MAX = 256 * 1024, 2 * 1024 * 1024


def gunzip_stats(path):
    """Return (decompressed_size, decompressed_sha256) streaming, or raise on a corrupt gzip."""
    h, n = hashlib.sha256(), 0
    with gzip.open(path, "rb") as g:
        for b in iter(lambda: g.read(1 << 20), b""):
            h.update(b); n += len(b)
    return n, h.hexdigest()


def build_manifest(d):
    out = {}
    for n, f in FILES.items():
        p = os.path.join(d, f)
        if f.endswith(".gz"):
            size, sha = gunzip_stats(p)
            out[n] = {"file": f, "encoding": "gzip", "decompressed_size": size, "decompressed_sha256": sha,
                      "compressed_size_min": GZ_SIZE_MIN, "compressed_size_max": GZ_SIZE_MAX,
                      "compressed_size_reference": os.path.getsize(p)}
        else:
            out[n] = {"file": f, "size": os.path.getsize(p), "sha256": sha256_file(p)}
    return {"version": 2, "unit": "MiB=2^20", "seed": SEED, "fixtures": out}


def resolve(manifest, d):
    """Fill in the on-disk (wire) size of gzip fixtures as m['size']; the server and byte floors use it.
    Call only after verify() passed."""
    for m in manifest["fixtures"].values():
        if m.get("encoding") == "gzip":
            m["size"] = os.path.getsize(os.path.join(d, m["file"]))
    return manifest


def load_manifest():
    with open(MANIFEST) as f:
        return json.load(f)


def verify(d, manifest=None):
    """Return list of problems (empty = OK)."""
    manifest = manifest or load_manifest()
    bad = []
    for n, m in manifest["fixtures"].items():
        p = os.path.join(d, m["file"])
        if not os.path.exists(p):
            bad.append(f"{n}: missing {p}"); continue
        if m.get("encoding") == "gzip":
            wire = os.path.getsize(p)
            if not m["compressed_size_min"] <= wire <= m["compressed_size_max"]:
                bad.append(f"{n}: compressed size {wire} outside {m['compressed_size_min']}..{m['compressed_size_max']}"); continue
            try:
                size, sha = gunzip_stats(p)
            except (OSError, EOFError) as e:
                bad.append(f"{n}: not a valid gzip ({e})"); continue
            if size != m["decompressed_size"]:
                bad.append(f"{n}: decompressed size {size} != {m['decompressed_size']}"); continue
            if sha != m["decompressed_sha256"]:
                bad.append(f"{n}: decompressed sha256 mismatch")
            continue
        if os.path.getsize(p) != m["size"]:
            bad.append(f"{n}: size {os.path.getsize(p)} != {m['size']}"); continue
        if sha256_file(p) != m["sha256"]:
            bad.append(f"{n}: sha256 mismatch")
    return bad


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("cmd", choices=["generate", "write-manifest", "verify"])
    ap.add_argument("--dir", default=os.path.join(HERE, "fixtures"))
    a = ap.parse_args(argv)
    if a.cmd == "generate":
        generate(a.dir); print("generated in", a.dir)
    elif a.cmd == "write-manifest":
        with open(MANIFEST, "w") as f:
            json.dump(build_manifest(a.dir), f, indent=2); f.write("\n")
        print("wrote", MANIFEST)
    else:
        bad = verify(a.dir)
        for b in bad: print("FIXTURE MISMATCH:", b, file=sys.stderr)
        print("fixtures OK" if not bad else "fixtures REFUSED")
        return 2 if bad else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
