"""Scenario definitions (data only). A-5 (early stop) changed what "read in full" means: a request with start_index 0 stops after the
window, so the scenarios that must consume the body ask for a `window`: "end" (the last WINDOW characters of the converted output,
G1/G2/G3/G4 form), "in-cap" (a window that ends ~200,000 characters before the end of the 5 MiB page's output, inside the cap of a
50 MiB chunked body, G7b), "beyond-cap" (start_index = the 5 MiB cap in characters, unreachable inside the cap, G5/G7c) or "start"
(start 0, early stop fires; the one scenario that is NOT a full-consumption sample). measure.py resolves the offsets and learns the
converted length of a page from the binary under test (a probe fetch past the end states it), see measure.resolve_window. IDs and gate assignment follow docs/BENCHMARK.md section 5.
`route` is a serve.py path; `expect` is "ok" or "too_large"; `min_bytes` is a callable(manifest)->int, the
valid-run floor for the server-side byte counter. implemented=False scenarios need fixtures/args E-2 supplies."""
from fixtures import REDIR_BODY, REDIR_FINAL, HOSTILE_SIZE, ATTRVALUE_SIZE
fixtures_hostile_size = lambda: ATTRVALUE_SIZE
MIB = 1024 * 1024
CAP = 5 * MIB
WINDOW = 100_000   # the default max_length cap in characters (FETCH_MAX_LENGTH_CAP): every window scenario asks for a full cap-size window
_size = lambda name: (lambda m: m["fixtures"][name]["size"])

SCENARIOS = {
    "idle":            dict(kind="idle", gate="G0,G4a,G4b", binary="shipped", implemented=True),
    # Idle RSS of the BENCH build (E-8: the idle delta versus the shipped build is bounded at 0.5 MiB). Recorded next to the
    # shipped figure; never a gate figure itself (gate "none"), and `idle` still refuses a bench-marked binary.
    "idle-bench":      dict(kind="idle", gate="none", binary="bench", implemented=True, ref="E-8 idle delta"),
    "g4a-5mib-full":   dict(kind="peak", gate="G4a", route="/5mb.html", args={"max_length": WINDOW}, window="end", expect="ok",
                            min_bytes=_size("html_5mib"), implemented=True, ref="G1/G2, window at the end (the read-in-full form of Sprint 4)"),
    "g4a-5mib-gz":     dict(kind="peak", gate="G4a", route="/5mb.html.gz", args={"max_length": WINDOW}, window="end", expect="ok",
                            min_bytes=_size("html_5mib_gz"), implemented=True, ref="G2, window at the end"),
    "g4a-late-landmark": dict(kind="peak", gate="G4a", route="/late-landmark.html", args={"max_length": WINDOW}, window="end", expect="ok",
                            min_bytes=_size("late_landmark"), implemented=True, ref="G4, window at the end"),
    "g4a-50mib-cl":    dict(kind="peak", gate="G4a", route="/50mb-cl.html", args={"max_length": WINDOW}, expect="too_large",
                            min_bytes=lambda m: 0,  # architecture 11.2: expected_min_bytes for G7a is zero (a correct client aborts on the Content-Length header, before any body write)
                            bounded_vs="g4a-5mib-full", implemented=True, ref="G7a"),
    "g4a-50mib-chunked": dict(kind="peak", gate="G4a", route="/50mb-chunked.html", args={"max_length": WINDOW}, window="beyond-cap", expect="too_large",
                            min_bytes=lambda m: CAP, bounded_vs="g4a-5mib-full", implemented=True, ref="chunked, window beyond the cap (the no-window form of Sprint 4 stops early since A-5; same request as g4b-window-beyond-cap)"),
    # 5 redirect hops, each with a body and (in the product) a fresh client build (A-3b fix-pass 1 note for E-2/E-4).
    # Recorded, outside the gating peak FIGURE (gate "none"), but intentionally fail-closed: an INVALID run or a median over the
    # peak target still fails the invocation (exit 2 / 1). `counter` is the serve.py counter key; floor = 5 hop bodies + the final body.
    "redirect-chain5": dict(kind="peak", gate="none", route="/redir/5", counter="/redir", expect="ok",
                            min_bytes=lambda m: 5 * REDIR_BODY + REDIR_FINAL, implemented=True, ref="redirect-chain memory check"),
    # G6 (E-4): 10 concurrent full reads of the 5 MiB page in ONE server process. Recorded for NFR-08 documentation, never a
    # pass/fail figure (verdict RECORDED, not in the gating peak); validity still counts: all 10 replies ok and >= 10 x 5 MiB
    # served, or the run is INVALID (exit 2).
    "g6-concurrent10": dict(kind="peak", gate="none", route="/5mb.html", args={"max_length": WINDOW}, window="end", expect="ok", concurrency=10,
                            recorded_only=True, min_bytes=lambda m: 10 * m["fixtures"]["html_5mib"]["size"], implemented=True,
                            ref="G6: 10 concurrent, recorded not gating; E-4"),
    # Fix-pass 1 (architect B2): adversarial-page peaks, 3 concurrent fetches (FETCH_MAX_CONCURRENCY) in one server process. RECORDED,
    # not a new gate: the pages are generated by serve.py from constants (no hash-pinned file), and the PRD/architecture define no
    # hostile-input gate. They still fail closed on validity (every reply must have the expected outcome, and the server must have
    # served the floor) and never enter the gating peak. `hostile-attrs3`: one 1.9 MiB start tag of tiny attributes, expected to be
    # refused with converter_limit (before the fix: converted, ~114 MB RSS each). `hostile-attrvalue3`: one 1.75 MiB attribute value (12.5% under the 2 MiB converter limit, so framing changes cannot flip it to a refusal),
    # expected to convert (the worst legitimate-shaped tag the tokenizer limit admits).
    "hostile-attrs3":  dict(kind="peak", gate="none", route="/hostile-attrs.html", args={"max_length": 5 * MIB}, expect="converter_limit",
                            concurrency=3, recorded_only=True, min_bytes=lambda m: 3 * 4096, implemented=True,   # floor stays low ON PURPOSE: the product may stop reading right after the refusal (early stop is correct here), so a high floor would reject a correct product; a ceiling test would need socket-buffer-stable byte counts, not cheap or stable, so early-refusal vs read-then-refuse is NOT distinguished here (RSS is what is recorded)
                            ref="hostile HTML: attribute bomb, 3 concurrent; fix-pass 1"),
    "hostile-attrvalue3": dict(kind="peak", gate="none", route="/hostile-attrvalue.html", args={"max_length": WINDOW}, window="end", expect="ok",
                            concurrency=3, recorded_only=True, min_bytes=lambda m: 3 * fixtures_hostile_size(), implemented=True,
                            ref="hostile HTML: one huge attribute value, 3 concurrent; fix-pass 1"),
    # G4b (A-5 window and early stop, A-6 raw). Windows are resolved by measure.py (see the header). G1 is the same request as
    # g4a-5mib-full (kept under its own id so G4b is self-contained); the 50 MiB chunked cases are bounded against it (G7b/G7c vs G1).
    "g4b-window-start": dict(kind="peak", gate="G4b", route="/5mb.html", args={"max_length": WINDOW}, window="start", expect="ok",
                            min_bytes=lambda m: WINDOW,   # the window's 100,000 characters need at least that many bytes, so a run that ends earlier never produced them
                            implemented=True, ref="window at start, early stop (not a full-consumption sample)"),
    "g4b-window-end":  dict(kind="peak", gate="G4b", route="/5mb.html", args={"max_length": WINDOW}, window="end", expect="ok",
                            min_bytes=_size("html_5mib"), implemented=True, ref="G1"),
    "g4b-raw":         dict(kind="peak", gate="G4b", route="/5mb.html", args={"max_length": WINDOW, "raw": True}, window="end", expect="ok",
                            min_bytes=_size("html_5mib"), raw_total="html_5mib", implemented=True, ref="G3"),
    "g4b-chunked-window-in-cap": dict(kind="peak", gate="G4b", route="/50mb-chunked.html", args={"max_length": WINDOW}, window="in-cap", expect="ok",
                            min_bytes="window", bounded_vs="g4b-window-end", implemented=True, ref="G7b"),
    "g4b-window-beyond-cap": dict(kind="peak", gate="G4b", route="/50mb-chunked.html", args={"max_length": WINDOW}, window="beyond-cap", expect="too_large",
                            min_bytes=lambda m: CAP, bounded_vs="g4b-window-end", implemented=True, ref="G5, G7c"),
}
GROUPS = {"g4a": [k for k, v in SCENARIOS.items() if v["gate"] == "G4a"],
          "g4b": [k for k, v in SCENARIOS.items() if v["gate"] == "G4b"]}
